@include('layouts.htmlheader')
@include('layouts.webnavheader')
         @yield('content')
@include('layouts.sectionfooter')
@include('layouts.jsfooterfront')
@include('layouts.scriptfooter')
         @yield('customscripts')
@include('layouts.htmlfooter')
